backend:
  name: git-gateway
  branch: master # Branch to update

publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

display_url: https://teaganatwater.com

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "recipes" # Used in routes
    label: "Recipes" # Used in the UI
    folder: "_cms/recipes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template
    fields: # The fields for each document, usually in front matter
      - label: "Path (include leading '/kitchen/recipe/')"
        name: "path"
        widget: "string"
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "recipe"
      - label: "Source"
        name: "source"
        widget: "string"
        required: false
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["Main dishes", "Sides", "Breads", "Desserts", "Cocktails"]
      - label: "Allergens"
        name: "allergens"
        widget: "list"
        fields:
          - label: "Common Allergen"
            name: "allergen"
            widget: "select"
            options: ["Dairy", "Egg", "Fish", "Gluten", "Tree nut", "Peanut", "Poultry", "Red meat", "Shellfish"]
          - label: "Contains Allergen"
            name: "allergenContained"
            widget: "boolean"
            default: true
        required: false
      - label: "Timing"
        name: "timing"
        widget: "list"
        fields:
          - label: "Timing Type"
            name: "timingType"
            widget: "select"
            options: ["Prep time", "Wait time", "Chill time", "Cook time", "Bake time"]
          - label: "Timing Amount"
            name: "timingAmount"
            widget: "string"
        required: false
      - label: "Total Time"
        name: "time"
        widget: "object"
        fields:
          - label: "Amount"
            name: "timeAmount"
            widget: "string"
          - label: "Units"
            name: "timeUnits"
            widget: "select"
            options: ["mins", "hrs"]
      - label: "Photo"
        name: "photo"
        widget: "image"
        required: false
      - label: "Ingredients"
        name: "ingredients"
        widget: "list"
        fields:
          - label: "Ingredient name"
            name: "ingredientName"
            widget: "string"
          - label: "Amount"
            name: "ingredientAmount"
            widget: "string"
          - label: "Modification"
            name: "ingredientModification"
            widget: "string"
        required: false
      - label: "Tools"
        name: "tools"
        widget: "list"
        fields:
          - label: "Tool name"
            name: "toolName"
            widget: "string"
        required: false
      - label: "Instructions"
        name: "instructions"
        widget: "list"
        fields:
          - label: "Step"
            name: "step"
            widget: "text"
      - label: "Notes"
        name: "notes"
        widget: "list"
        fields:
          - label: "Note"
            name: "note"
            widget: "text"
        required: false
